In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[2.0, 4.0, 1.0, 8.0], [2.5, 7.3, 9.0, 2.3]])
print(b)

[[2.  4.  1.  8. ]
 [2.5 7.3 9.  2.3]]


In [4]:
# get dimension
a.ndim

1

In [5]:
#get shape
b.shape

(2, 4)

In [6]:
a.dtype

dtype('int16')

In [7]:
#get size
a.itemsize

2

In [8]:
#get total size
b.size

8

In [9]:
b.nbytes

64

In [10]:
b.itemsize * b.size

64

In [11]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
#get a specific element
c[1, 3]

11

In [13]:
#get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#get a specific column
c[:, 2]

array([ 3, 10])

In [15]:
#getting a little more funcy
c[0, 1:6:2]

array([2, 4, 6])

In [16]:
#getting a little more funcy
c[0, 1:-1:2]

array([2, 4, 6])

In [17]:
#getting a little more funcy
c[0, 1:6]

array([2, 3, 4, 5, 6])

In [18]:
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
c[0, 4]  = 90
print(c)

[[ 1  2  3  4 90  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
c[0, 4]  = 90
print(c)
c[:,2] = 5
print(c)

[[ 1  2  3  4 90  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  5  4 90  6  7]
 [ 8  9  5 11 12 13 14]]


In [21]:
c[:, 5] = [34, 54]
print(c)

[[ 1  2  5  4 90 34  7]
 [ 8  9  5 11 12 54 14]]


In [22]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
d[1,0,1]

6

In [24]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [25]:
d[:,1,1]

array([4, 8])

In [26]:
d[1,:,0]

array([5, 7])

In [27]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
d[:, 1, 1]

array([4, 8])

In [29]:
#replace
d[:,1,:] = [[9,9],[8,8]]
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [30]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.ones((2,4,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [32]:
np.full((2,2), 55, dtype='float32')

array([[55., 55.],
       [55., 55.]], dtype=float32)

In [33]:
h = np.array([2, 5, 6, 8])
print(h)

[2 5 6 8]


In [34]:
np.full_like(h, 3)

array([3, 3, 3, 3])

In [35]:
np.random.rand(2,3)

array([[0.22561824, 0.7838163 , 0.72764711],
       [0.38315734, 0.37490837, 0.85093377]])

In [36]:
np.random.random_sample(h.shape)

array([0.16981679, 0.26849209, 0.43492773, 0.95222399])

In [37]:
np.random.randint(2,9, size=(3,3))

array([[8, 5, 3],
       [5, 5, 2],
       [2, 8, 8]])

In [38]:
np.identity(4, dtype='int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [39]:
#repeat an array
arr= np.array([[1,2,3]])
r = np.repeat(arr,3, axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
output = np.ones((5,5))
print(output)
zeros = np.zeros((3,3))
print(zeros)
zeros[1,1] = 9
print(zeros)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [44]:
output[1:4,1:4] = zeros
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
f = np.array([1,2,3])
g=f
print(g)

[1 2 3]


In [51]:
j = np.array([1,2,3])
k = j.copy()
j[1] = 4
print(j)
print(k)

[1 4 3]
[1 2 3]


In [54]:
#Mathematics

In [55]:
a = np.array([1,2,3])


In [56]:
a+2

array([3, 4, 5])

In [57]:
a-2

array([-1,  0,  1])

In [58]:
a*2

array([2, 4, 6])

In [60]:
a/2

array([0.5, 1. , 1.5])

In [61]:
b = np.array([2,6,3])
a+b

array([3, 8, 6])

In [62]:
a**2

array([1, 4, 9])

In [63]:
#take the sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

#### Linear Algebra

In [70]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [73]:
#find the determinant
a = np.identity(3)
np.linalg.det(a)

1.0

#### Statistics

In [82]:
st = np.array([[1,2,3],[4,5,6]])
print(st)

[[1 2 3]
 [4 5 6]]


In [75]:
np.max(st)

6

In [79]:
np.max(st, axis=1)

array([3, 6])

In [81]:
np.sum(st, axis=0)

array([5, 7, 9])

#### Reorganizing arrays

In [85]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [88]:
#vertically stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [90]:
#horizontally stack
h1 = np.array([4,6,3,8])
h2 = np.array([7,2,0,1])
print(h1)
print(h2)
np.hstack((h1,h2))

[4 6 3 8]
[7 2 0 1]


array([4, 6, 3, 8, 7, 2, 0, 1])

## Load data from file

In [98]:
filedata = np.genfromtxt('data55.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [99]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [100]:
filedata[filedata>40]

array([196,  75,  42, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [101]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[3,5,4]]

array([4, 6, 5])

In [102]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [103]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])